on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
  MAVEN_HOME: /opt/maven

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o JDK 17 com Adoptium (temurin)
      - name: Set up JDK 17 (Adoptium Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Git LFS
        run: git lfs install

      - name: List Git LFS files
        run: git lfs ls-files

      - name: Pull Git LFS files
        run: git lfs pull

      # Passo 3: Instalar o Maven no Ubuntu
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Passo 4: Navegar até o diretório correto e rodar o Maven
      - name: Build with Maven
        run: |
          cd auth  # Navegar para o diretório onde está o pom.xml
          mvn clean install -DskipTests

      # Passo 5: Criar a imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t anajumedina/my-java-app:${GITHUB_SHA} ./auth

      # Passo 6: Login no Docker Hub e Push da imagem
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Registry
        run: docker push anajumedina/my-java-app:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Passo 1: Decodificar o kubeconfig do segredo base64
      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
          # Verificar se o KUBECONFIG foi configurado corretamente
          cat $KUBECONFIG

      # Passo 2: Configurar kubectl
      - name: Configurar kubectl
        run: |
          kubectl config get-contexts
          kubectl config set-context docker-desktop --cluster=docker-desktop --user=docker-desktop --namespace=default
          kubectl config use-context docker-desktop

      # Passo 3: Aplicar o Kubernetes Deployment
      - name: Aplicar o Kubernetes Deployment
        run: |
          pwd
          cd ..
          ls -R /home/runner/work/auth
          sudo find /home/runner/work/auth/auth -name "deployment.yaml"
          kubectl apply -f kubernetes/deployment.yaml

      # Passo 4: Verificar Pods no Kubernetes
      - name: Verificar Pods no Kubernetes
        run: |
          kubectl get pods
